// src/mockData.js — demo-mode product data for admin panel when backend is offline
// Mirrors frontend/src/api/mockAPI.js structure (id, name, price, category, image, description)

const menuData = [
  { id: 1, name: "اسپرسو (۷۰ ربوستا)", price: 65, category: "اسپرسوبار", image: "/images/espresso.jpg", description: "یک شات اسپرسوی غلیظ و پرکافئین با کرمای غنی و طعمی قدرتمند، ایده‌آل برای شروع یک روز پرانرژی." },
  { id: 2, name: "اسپرسو ۵۰×۵۰", price: 75, category: "اسپرسوبار", image: "/images/espresso.jpg", description: "ترکیبی متعادل از دانه‌های عربیکا و ربوستا که طعمی کلاسیک و عطری دلنشین را به ارمغان می‌آورد." },
  { id: 3, name: "اسپرسو ۷۰ عربیکا", price: 80, category: "اسپرسوبار", image: "/images/espresso.jpg", description: "اسیدیته ملایم و طعم‌های میوه‌ای و گلی دانه‌های عربیکا در یک شات اسپرسوی لطیف و معطر." },
  { id: 4, name: "اسپرسو بلند عربیکا", price: 80, category: "اسپرسوبار", image: "/images/espresso.jpg", description: "اسپرسوی تازه‌رست با کرمای غنی و طعمی متعادل؛ تخصص مهراس." },
  { id: 5, name: "کلمبیا", price: 90, category: "اسپرسوبار", image: "/images/espresso.jpg", description: "قهوه‌ای تک‌خاستگاه با طعم‌یادهای آجیلی و شکلاتی و تن‌واری (Body) متوسط، تجربه‌ای کلاسیک و دلپذیر." },
  { id: 6, name: "اتیوپی", price: 90, category: "اسپرسوبار", image: "/images/espresso.jpg", description: "اسپرسوی تازه‌رست با کرمای غنی و طعمی متعادل؛ تخصص مهراس." },
  { id: 7, name: "ریسترتو", price: 65, category: "اسپرسوبار", image: "/images/espresso.jpg", description: "عصاره‌ای کوتاه‌تر و غلیظ‌تر از اسپرسو با شیرینی بیشتر و تلخی کمتر، نهایت طعم قهوه در یک جرعه." },
  { id: 8, name: "لانگو", price: 65, category: "اسپرسوبار", image: "/images/espresso.jpg", description: "اسپرسوی تازه‌رست با کرمای غنی و طعمی متعادل؛ تخصص مهراس." },
  { id: 9, name: "قهوه دمی چک‌ای", price: 150, category: "اسپرسوبار", image: "/images/espresso.jpg", description: "قهوه‌ای صاف و شفاف با طعم‌های پیچیده که به آرامی دم‌آوری شده تا بهترین ویژگی‌های دانه قهوه را آزاد کند." },
  { id: 10, name: "قهوه دمی غوطه‌وری", price: 150, category: "اسپرسوبار", image: "/images/espresso.jpg", description: "اسپرسوی تازه‌رست با کرمای غنی و طعمی متعادل؛ تخصص مهراس." },
  { id: 11, name: "اسپشیالتی", price: null, category: "اسپرسوبار", image: "/images/espresso.jpg", description: "قهوه‌های تک‌خاستگاه و کمیاب از سراسر جهان که به صورت روزانه تغییر می‌کنند. لطفاً برای اطلاع از دانه‌های امروز و قیمت از باریستا سوال بفرمایید." },
  { id: 12, name: "کاپوچینو", price: 100, category: "هات درینک", image: "/images/latte-art.jpg", description: "گرم و دلنشین، با دانه‌های تازه و شیر تازهٔ روز." },
  { id: 13, name: "کاپوچینو کلاسیک", price: 90, category: "هات درینک", image: "/images/latte-art.jpg", description: "ترکیب سنتی اسپرسو، شیر بخار داده شده و فوم شیر غلیظ، یک انتخاب کلاسیک و همیشگی." },
  { id: 14, name: "لته", price: 90, category: "هات درینک", image: "/images/latte-art.jpg", description: "اسپرسوی غنی به همراه مقدار زیادی شیر بخار داده شده و لایه‌ای نازک از فوم، نوشیدنی‌ای لطیف و خامه‌ای." },
  { id: 15, name: "لته لوکس", price: 120, category: "هات درینک", image: "/images/latte-art.jpg", description: "گرم و دلنشین، با دانه‌های تازه و شیر تازهٔ روز." },
  { id: 16, name: "هات چاکلت", price: 110, category: "هات درینک", image: "/images/latte-art.jpg", description: "شکلات تلخ بلژیکی ذوب شده در شیر داغ، نوشیدنی‌ای غلیظ، غنی و آرامش‌بخش برای تمام فصول." },
  { id: 17, name: "وایت چاکلت", price: 90, category: "هات درینک", image: "/images/latte-art.jpg", description: "گرم و دلنشین، با دانه‌های تازه و شیر تازهٔ روز." },
  { id: 18, name: "پرو چاکلت لایس", price: 170, category: "هات درینک", image: "/images/latte-art.jpg", description: "گرم و دلنشین، با دانه‌های تازه و شیر تازهٔ روز." },
  { id: 19, name: "موکاچینو", price: 105, category: "هات درینک", image: "/images/latte-art.jpg", description: "گرم و دلنشین، با دانه‌های تازه و شیر تازهٔ روز." },
  { id: 20, name: "موکا", price: 110, category: "هات درینک", image: "/images/latte-art.jpg", description: "ترکیبی بهشتی از اسپرسو، شکلات داغ و شیر بخار داده شده، بهترین انتخاب برای دوستداران قهوه و شکلات." },
  { id: 21, name: "کارامل ماکیاتو", price: 100, category: "هات درینک", image: "/images/latte-art.jpg", description: "گرم و دلنشین، با دانه‌های تازه و شیر تازهٔ روز." },
  { id: 22, name: "کورتادو", price: 70, category: "هات درینک", image: "/images/latte-art.jpg", description: "گرم و دلنشین، با دانه‌های تازه و شیر تازهٔ روز." },
  { id: 23, name: "گلدن اسپرسو", price: 125, category: "هات درینک", image: "/images/latte-art.jpg", description: "گرم و دلنشین، با دانه‌های تازه و شیر تازهٔ روز." },
  { id: 24, name: "نسکافه", price: 85, category: "هات درینک", image: "/images/latte-art.jpg", description: "گرم و دلنشین، با دانه‌های تازه و شیر تازهٔ روز." },
  { id: 25, name: "ماسالا", price: 75, category: "هات درینک", image: "/images/latte-art.jpg", description: "چای شیرین و تند هندی با ترکیبی از ادویه‌های گرم مانند زنجبیل، هل و دارچین، نوشیدنی‌ای معطر و انرژی‌بخش." },
  { id: 26, name: "کرک", price: 90, category: "هات درینک", image: "/images/latte-art.jpg", description: "ترکیبی خاص و معطر از چای، هل، زعفران و شکلات که طعمی فراموش‌نشدنی را خلق می‌کند." },
  { id: 27, name: "شیرداغ", price: 30, category: "هات درینک", image: "/images/latte-art.jpg", description: "گرم و دلنشین، با دانه‌های تازه و شیر تازهٔ روز." },
  { id: 28, name: "آیس امریکانو", price: 95, category: "آیس", image: "/images/iced-coffee.jpg", description: "سرد و خنک؛ ترکیب تازهٔ اسپرسو با یخ و شیر." },
  { id: 29, name: "آیس چاکلت", price: 130, category: "آیس", image: "/images/iced-coffee.jpg", description: "سرد و خنک؛ ترکیب تازهٔ اسپرسو با یخ و شیر." },
  { id: 30, name: "آیس موکا", price: 150, category: "آیس", image: "/images/iced-coffee.jpg", description: "سرد و خنک؛ ترکیب تازهٔ اسپرسو با یخ و شیر." },
  { id: 31, name: "آیس موکاچینو", price: 170, category: "آیس", image: "/images/iced-coffee.jpg", description: "سرد و خنک؛ ترکیب تازهٔ اسپرسو با یخ و شیر." },
  { id: 32, name: "آیس کارامل ماکیاتو", price: 160, category: "آیس", image: "/images/iced-coffee.jpg", description: "سرد و خنک؛ ترکیب تازهٔ اسپرسو با یخ و شیر." },
  { id: 33, name: "آیس لته", price: 110, category: "آیس", image: "/images/iced-coffee.jpg", description: "سرد و خنک؛ ترکیب تازهٔ اسپرسو با یخ و شیر." },
  { id: 34, name: "آیس لته سیروپ", price: 150, category: "آیس", image: "/images/iced-coffee.jpg", description: "سرد و خنک؛ ترکیب تازهٔ اسپرسو با یخ و شیر." },
  { id: 35, name: "آیس کرک", price: 100, category: "آیس", image: "/images/iced-coffee.jpg", description: "سرد و خنک؛ ترکیب تازهٔ اسپرسو با یخ و شیر." },
  { id: 36, name: "آیس نسکافه", price: 110, category: "آیس", image: "/images/iced-coffee.jpg", description: "سرد و خنک؛ ترکیب تازهٔ اسپرسو با یخ و شیر." },
  { id: 37, name: "کارامل دریم", price: 75, category: "ویواید دریم", image: "/images/pour-over.jpg", description: "رویای وویاید؛ لایه‌های کرمی با طعم‌های خاص." },
  { id: 38, name: "کوکونات دریم", price: 75, category: "ویواید دریم", image: "/images/pour-over.jpg", description: "رویای وویاید؛ لایه‌های کرمی با طعم‌های خاص." },
  { id: 39, name: "وانیلا دریم", price: 75, category: "ویواید دریم", image: "/images/pour-over.jpg", description: "رویای وویاید؛ لایه‌های کرمی با طعم‌های خاص." },
  { id: 40, name: "سینامون دریم", price: 75, category: "ویواید دریم", image: "/images/pour-over.jpg", description: "رویای وویاید؛ لایه‌های کرمی با طعم‌های خاص." },
  { id: 41, name: "چاکلت دریم", price: 75, category: "ویواید دریم", image: "/images/pour-over.jpg", description: "رویای وویاید؛ لایه‌های کرمی با طعم‌های خاص." },
  { id: 42, name: "هزل دریم", price: 75, category: "ویواید دریم", image: "/images/pour-over.jpg", description: "رویای وویاید؛ لایه‌های کرمی با طعم‌های خاص." },
  { id: 43, name: "آیریش دریم", price: 75, category: "ویواید دریم", image: "/images/pour-over.jpg", description: "رویای وویاید؛ لایه‌های کرمی با طعم‌های خاص." },
  { id: 44, name: "چای ایرانی", price: 45, category: "دمی بار", image: "/images/pour-over.jpg", description: "دم‌آوری آرام با دانه‌های تک‌خاستگاه؛ عطر و طعم تمام‌عیار." },
  { id: 45, name: "چای ترش", price: 60, category: "دمی بار", image: "/images/pour-over.jpg", description: "دم‌آوری آرام با دانه‌های تک‌خاستگاه؛ عطر و طعم تمام‌عیار." },
  { id: 46, name: "چای سبز", price: 50, category: "دمی بار", image: "/images/pour-over.jpg", description: "دم‌آوری آرام با دانه‌های تک‌خاستگاه؛ عطر و طعم تمام‌عیار." },
  { id: 47, name: "معجون چایی", price: 70, category: "دمی بار", image: "/images/pour-over.jpg", description: "دم‌آوری آرام با دانه‌های تک‌خاستگاه؛ عطر و طعم تمام‌عیار." },
  { id: 48, name: "دمنوش بهشت", price: 65, category: "دمی بار", image: "/images/pour-over.jpg", description: "دم‌آوری آرام با دانه‌های تک‌خاستگاه؛ عطر و طعم تمام‌عیار." },
  { id: 49, name: "دمنوش انرژی", price: 60, category: "دمی بار", image: "/images/pour-over.jpg", description: "دم‌آوری آرام با دانه‌های تک‌خاستگاه؛ عطر و طعم تمام‌عیار." },
  { id: 50, name: "دمنوش آروما", price: 65, category: "دمی بار", image: "/images/pour-over.jpg", description: "دم‌آوری آرام با دانه‌های تک‌خاستگاه؛ عطر و طعم تمام‌عیار." },
  { id: 51, name: "کارامل", price: 40, category: "سیروپ", image: "/images/syrup.jpg", description: "سیروپ‌های دست‌ساز مهراس برای نوشیدنی دلخواه شما." },
  { id: 52, name: "نارگیل", price: 40, category: "سیروپ", image: "/images/syrup.jpg", description: "سیروپ‌های دست‌ساز مهراس برای نوشیدنی دلخواه شما." },
  { id: 53, name: "وانیل", price: 40, category: "سیروپ", image: "/images/syrup.jpg", description: "سیروپ‌های دست‌ساز مهراس برای نوشیدنی دلخواه شما." },
  { id: 54, name: "فندق", price: 40, category: "سیروپ", image: "/images/syrup.jpg", description: "سیروپ‌های دست‌ساز مهراس برای نوشیدنی دلخواه شما." },
  { id: 55, name: "توت‌فرنگی", price: 40, category: "سیروپ", image: "/images/syrup.jpg", description: "سیروپ‌های دست‌ساز مهراس برای نوشیدنی دلخواه شما." },
  { id: 56, name: "قهوه ویژه", price: 200, category: "کیک و دسر", image: "/images/dessert.jpg", description: "دسرهای خانگی مهراس، تازه هر روز." },
  { id: 57, name: "چیزکیک", price: 150, category: "کیک و دسر", image: "/images/dessert.jpg", description: "دسرهای خانگی مهراس، تازه هر روز." },
  { id: 58, name: "کیک شکلاتی", price: 130, category: "کیک و دسر", image: "/images/dessert.jpg", description: "دسرهای خانگی مهراس، تازه هر روز." },
];

export default menuData;
